### ISSUE TITLE
Update input parameters for cladetime's assign_clades CLI

### ISSUE THREAD

**Issue by elray1** [reichlab/cladetime#6]
We will typically just need to get clade assignments (and summarize to counts of clade assignments) for samples that were collected within a particular date range.  We should be able to specify those dates as part of a call to `assign_clades`.  This is related to discussion in reichlab/variant-nowcast-hub#3 in that we'll need to be sure that when we pull the sequence data, we get everything that has a collection date within the specified range.

For more specificity, here's a suggestion that I'm not at all committed to: we could introduce command line arguments `seq_start_date` and `seq_end_date` and keep anything with `seq_start_date <= collection_date <= seq_end_date`.

**2024-10-24: Definition of done**

A lot has changed since May! The latest thinking of @elray1 and @bsweger about the `assign_clades` options:

- [ ] `sequence_collection_min_date`: assign clades to sequences collected on or after this date (UTC midnight)
- [ ] `sequence_collection_max_date`: assign clades to sequences collected on or before this date (UTC midnight)
- [ ] `sequence_as_of`: use the Nextstrain sequence data as it existed on this date (UTC midnight)
- [ ] `tree_as_of`: use the Nextstrain referernce tree as it existed on this date (UTC midnight)
- [ ] `data_dir`: where to save the output

**Comment by bsweger** [comment]
Closing this because we've decided not to implement the CLI at this time.
